[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  VITE_HELIUS_RPC_URL = "https://mainnet.helius-rpc.com/?api-key=e4e7f06a-1e90-4628-8b07-d4f3c30fc5c9"
  VITE_GRIN_TOKEN_ADDRESS = "7JofsgKgD3MerQDa7hEe4dfkY3c3nMnsThZzUuYyTFpE"
  VITE_SOLANA_TRACKER_API_KEY = "91a88295-acb4-4f38-b9af-3cd58b69856b"
  VITE_GRIN_RECEIVER_ADDRESS = "7JofsgKgD3MerQDa7hEe4dfkY3c3nMnsThZzUuYyTFpE"
  VITE_SUPABASE_URL = "https://guzlanuvzfgcekmupcrx.supabase.co"
  VITE_REPLICATE_API_TOKEN = "r8_AqmMkNzyqbVJf5fGMCFhYnKckurssUf0SwUzU"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
